# to use black/mypy/flake8 I use pre-commit: 
# https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/


[tool.pytest.ini_options]
pythonpath = [
  "."
]

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv6
  | _build
  | buck-out
  | build
  | dist
)/
'''

[flake8]
max-line-length = 79
max-complexity = 18

[tool.isort]
profile = "black"  # see: https://pycqa.github.io/isort/docs/configuration/black_compatibility.html
